-- Create waitlist table
create table if not exists public.waitlist (
  id uuid default gen_random_uuid() primary key,
  brand_name text not null,
  instagram text not null,
  category text not null,
  email text not null,
  whatsapp text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  waitlist_number int8 generated by default as identity (start with 101)
);

-- Indexes for quick lookups and case-insensitive uniqueness constraints
create unique index if not exists waitlist_email_idx on public.waitlist (lower(email));
create unique index if not exists waitlist_instagram_idx on public.waitlist (lower(regexp_replace(instagram, '^@', '')));

-- Enable RLS (Row Level Security)
-- Note: Since the backend API handler queries the database using the Service Role Key,
-- this key bypasses RLS policies automatically. This is safe and secure for server-side operations.
alter table public.waitlist enable row level security;
